"""Kerr boson-cloud spectra, tides, and archived exceptional-point baselines."""

from .ep import analytic_far_tide_q_ep, find_ep_roots
from .dynamics import evolve_transition
from .formation import assess_formation_history
from .certification import (
    compare_schwarzschild_benchmark,
    direct_ward_audit,
    fit_weak_field_limit,
    operator_form_audit,
    ward_identity_audit,
)
from .models import (
    AtlasConfig,
    BenchmarkResult,
    CFSettings,
    EffectWidthResult,
    EPResult,
    EvolutionConfig,
    EvolutionResult,
    FormationConfig,
    FormationResult,
    GaugeAuditResult,
    GaugeMetricConfig,
    GaugeMetricResult,
    GaugeVectorSpec,
    KernelErrorBudgetResult,
    ContourKernelSettings,
    ContourModeResult,
    HighOrderTideBudgetResult,
    IndependentKernelResult,
    KerrModeResult,
    KerrModeSettings,
    PhenomenologyResult,
    MultipoleEtaResult,
    MultipoleKernelResult,
    MultipoleTideSettings,
    RelativisticTideSettings,
    SaturationResult,
    State,
    TimescaleResult,
    TransitionConfig,
    TransitionKernelResult,
    TransitionResult,
    WardAuditResult,
    WeakFieldFitResult,
    WidthScanConfig,
)
from .relativity import (
    quasibound_frequency_cf,
    saturation_spin_cf,
    solve_kerr_mode,
    solve_kerr_mode_adaptive,
    solve_saturation_mode_cf,
    trace_saturation_branch_cf,
)
from .relativistic_tides import (
    compute_kernel_error_budget,
    compute_relativistic_transition,
    compute_transition_kernel,
    covariant_tidal_kernel_M,
    evaluate_transition_at_q,
    gauge_audit_transition,
    relativistic_tidal_eta_M,
    scan_relativistic_atlas,
    schwarzschild_irg_tidal_kernel_M,
    schwarzschild_newtonian_tidal_kernel_M,
    schwarzschild_rw_tidal_kernel_M,
)
from .kernel_validation import (
    compute_high_order_tide_budget,
    independent_kerr_kernel_M,
    newtonian_exact_companion_eta_M,
    newtonian_multipole_kernel_M,
    solve_kerr_mode_contour,
    validate_kerr_kernel,
)
from .tidal_metric import compact_support_gauge_metric
from .spectrum import (
    gamma_detweiler_M,
    omega_real_M,
    saturation_spin_approx,
    saturation_spin_numeric,
)
from .tides import resonance_frequency_M, tidal_eta_at_omega_M, tidal_eta_M
from .timescales import compute_timescales
from .width import compute_near_ep_width

__all__ = [
    "AtlasConfig",
    "BenchmarkResult",
    "CFSettings",
    "EffectWidthResult",
    "EPResult",
    "EvolutionConfig",
    "EvolutionResult",
    "FormationConfig",
    "FormationResult",
    "GaugeAuditResult",
    "GaugeMetricConfig",
    "GaugeMetricResult",
    "GaugeVectorSpec",
    "KernelErrorBudgetResult",
    "ContourKernelSettings",
    "ContourModeResult",
    "HighOrderTideBudgetResult",
    "IndependentKernelResult",
    "KerrModeResult",
    "KerrModeSettings",
    "PhenomenologyResult",
    "MultipoleEtaResult",
    "MultipoleKernelResult",
    "MultipoleTideSettings",
    "RelativisticTideSettings",
    "SaturationResult",
    "State",
    "TimescaleResult",
    "TransitionConfig",
    "TransitionKernelResult",
    "TransitionResult",
    "WardAuditResult",
    "WeakFieldFitResult",
    "WidthScanConfig",
    "analytic_far_tide_q_ep",
    "assess_formation_history",
    "compute_near_ep_width",
    "compute_kernel_error_budget",
    "compute_high_order_tide_budget",
    "compute_relativistic_transition",
    "compute_transition_kernel",
    "compare_schwarzschild_benchmark",
    "compact_support_gauge_metric",
    "compute_timescales",
    "covariant_tidal_kernel_M",
    "direct_ward_audit",
    "evolve_transition",
    "evaluate_transition_at_q",
    "find_ep_roots",
    "fit_weak_field_limit",
    "gamma_detweiler_M",
    "gauge_audit_transition",
    "omega_real_M",
    "independent_kerr_kernel_M",
    "newtonian_exact_companion_eta_M",
    "newtonian_multipole_kernel_M",
    "operator_form_audit",
    "quasibound_frequency_cf",
    "relativistic_tidal_eta_M",
    "resonance_frequency_M",
    "saturation_spin_approx",
    "saturation_spin_cf",
    "saturation_spin_numeric",
    "scan_relativistic_atlas",
    "schwarzschild_irg_tidal_kernel_M",
    "schwarzschild_newtonian_tidal_kernel_M",
    "schwarzschild_rw_tidal_kernel_M",
    "solve_kerr_mode",
    "solve_kerr_mode_contour",
    "solve_kerr_mode_adaptive",
    "solve_saturation_mode_cf",
    "tidal_eta_at_omega_M",
    "tidal_eta_M",
    "trace_saturation_branch_cf",
    "validate_kerr_kernel",
    "ward_identity_audit",
]
